/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package favo;
import io.reactivex.Observable;

public class App {
    public static void main(String[] args) {
        Observable<String> observable = Observable.just("Hello, world");
        observable.subscribe(System.out::println);
	Observable observable1 = Observable.just("A", "B", "C", "D", "E");
	// observer 1
	observable1.subscribe(val -> {
	// "A", "B", "C", "D", "E" will be received in order
	});
	// observer 2
	observable1.subscribe(val -> {
	// Again, "A", "B", "C", "D", "E" will be received in order
	});
	observable1.subscribe(System.out::println);
    }
	public static <T> Observable just(T item) {
		return Observable.create(emitter -> {
		emitter.onNext(item);
		emitter.onComplete();
	});
	}
}